// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package game

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BunicaEvent struct {
	_tab flatbuffers.Table
}

func GetRootAsBunicaEvent(buf []byte, offset flatbuffers.UOffsetT) *BunicaEvent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BunicaEvent{}
	x.Init(buf, n+offset)
	return x
}

func FinishBunicaEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBunicaEvent(buf []byte, offset flatbuffers.UOffsetT) *BunicaEvent {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BunicaEvent{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBunicaEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *BunicaEvent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BunicaEvent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BunicaEvent) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func BunicaEventStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func BunicaEventAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func BunicaEventEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
