// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package game

import "strconv"

type EventKind byte

const (
	EventKindNilEvent           EventKind = 0
	EventKindPlayerHello        EventKind = 1
	EventKindPlayerQuit         EventKind = 2
	EventKindPlayerJoined       EventKind = 3
	EventKindPlayerJoinedList   EventKind = 4
	EventKindPlayerHelloConfirm EventKind = 5
	EventKindPlayerMovedList    EventKind = 6
	EventKindPlayerMoved        EventKind = 7
)

var EnumNamesEventKind = map[EventKind]string{
	EventKindNilEvent:           "NilEvent",
	EventKindPlayerHello:        "PlayerHello",
	EventKindPlayerQuit:         "PlayerQuit",
	EventKindPlayerJoined:       "PlayerJoined",
	EventKindPlayerJoinedList:   "PlayerJoinedList",
	EventKindPlayerHelloConfirm: "PlayerHelloConfirm",
	EventKindPlayerMovedList:    "PlayerMovedList",
	EventKindPlayerMoved:        "PlayerMoved",
}

var EnumValuesEventKind = map[string]EventKind{
	"NilEvent":           EventKindNilEvent,
	"PlayerHello":        EventKindPlayerHello,
	"PlayerQuit":         EventKindPlayerQuit,
	"PlayerJoined":       EventKindPlayerJoined,
	"PlayerJoinedList":   EventKindPlayerJoinedList,
	"PlayerHelloConfirm": EventKindPlayerHelloConfirm,
	"PlayerMovedList":    EventKindPlayerMovedList,
	"PlayerMoved":        EventKindPlayerMoved,
}

func (v EventKind) String() string {
	if s, ok := EnumNamesEventKind[v]; ok {
		return s
	}
	return "EventKind(" + strconv.FormatInt(int64(v), 10) + ")"
}
