// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package game

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type KindHolder struct {
	_tab flatbuffers.Table
}

func GetRootAsKindHolder(buf []byte, offset flatbuffers.UOffsetT) *KindHolder {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &KindHolder{}
	x.Init(buf, n+offset)
	return x
}

func FinishKindHolderBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsKindHolder(buf []byte, offset flatbuffers.UOffsetT) *KindHolder {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &KindHolder{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedKindHolderBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *KindHolder) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *KindHolder) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *KindHolder) Kind() EventKind {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return EventKind(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *KindHolder) MutateKind(n EventKind) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func KindHolderStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func KindHolderAddKind(builder *flatbuffers.Builder, kind EventKind) {
	builder.PrependByteSlot(0, byte(kind), 0)
}
func KindHolderEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
