// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package game

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PlayerHelloConfirm struct {
	_tab flatbuffers.Table
}

func GetRootAsPlayerHelloConfirm(buf []byte, offset flatbuffers.UOffsetT) *PlayerHelloConfirm {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PlayerHelloConfirm{}
	x.Init(buf, n+offset)
	return x
}

func FinishPlayerHelloConfirmBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPlayerHelloConfirm(buf []byte, offset flatbuffers.UOffsetT) *PlayerHelloConfirm {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PlayerHelloConfirm{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPlayerHelloConfirmBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PlayerHelloConfirm) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PlayerHelloConfirm) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PlayerHelloConfirm) Id() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PlayerHelloConfirm) MutateId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func PlayerHelloConfirmStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PlayerHelloConfirmAddId(builder *flatbuffers.Builder, id int32) {
	builder.PrependInt32Slot(0, id, 0)
}
func PlayerHelloConfirmEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
