// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package game

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PlayerQuit struct {
	_tab flatbuffers.Table
}

func GetRootAsPlayerQuit(buf []byte, offset flatbuffers.UOffsetT) *PlayerQuit {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PlayerQuit{}
	x.Init(buf, n+offset)
	return x
}

func FinishPlayerQuitBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPlayerQuit(buf []byte, offset flatbuffers.UOffsetT) *PlayerQuit {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PlayerQuit{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPlayerQuitBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PlayerQuit) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PlayerQuit) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PlayerQuit) Id() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PlayerQuit) MutateId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func PlayerQuitStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PlayerQuitAddId(builder *flatbuffers.Builder, id int32) {
	builder.PrependInt32Slot(0, id, 0)
}
func PlayerQuitEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
