// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package game

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PlayerHello struct {
	_tab flatbuffers.Table
}

func GetRootAsPlayerHello(buf []byte, offset flatbuffers.UOffsetT) *PlayerHello {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PlayerHello{}
	x.Init(buf, n+offset)
	return x
}

func FinishPlayerHelloBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPlayerHello(buf []byte, offset flatbuffers.UOffsetT) *PlayerHello {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PlayerHello{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPlayerHelloBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PlayerHello) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PlayerHello) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PlayerHello) Id() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PlayerHello) MutateId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func PlayerHelloStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PlayerHelloAddId(builder *flatbuffers.Builder, id int32) {
	builder.PrependInt32Slot(0, id, 0)
}
func PlayerHelloEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
