// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package game

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PlayerMoved struct {
	_tab flatbuffers.Table
}

func GetRootAsPlayerMoved(buf []byte, offset flatbuffers.UOffsetT) *PlayerMoved {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PlayerMoved{}
	x.Init(buf, n+offset)
	return x
}

func FinishPlayerMovedBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPlayerMoved(buf []byte, offset flatbuffers.UOffsetT) *PlayerMoved {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PlayerMoved{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPlayerMovedBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PlayerMoved) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PlayerMoved) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PlayerMoved) Player(obj *Player) *Player {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Player)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func PlayerMovedStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PlayerMovedAddPlayer(builder *flatbuffers.Builder, player flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(player), 0)
}
func PlayerMovedEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
