// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export { BunicaEvent } from './game/bunica-event.js';
export { Event } from './game/event.js';
export { Player } from './game/player.js';
export { PlayerHello } from './game/player-hello.js';
export { PlayerHelloConfirm } from './game/player-hello-confirm.js';
export { PlayerJoined } from './game/player-joined.js';
export { PlayerMoved } from './game/player-moved.js';
export { PlayerQuit } from './game/player-quit.js';
