// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum EventKind {
  NilEvent = 0,
  PlayerHello = 1,
  PlayerQuit = 2,
  PlayerJoined = 3,
  PlayerJoinedList = 4,
  PlayerHelloConfirm = 5,
  PlayerMovedList = 6,
  PlayerMoved = 7
}
