// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export var EventKind;
(function (EventKind) {
    EventKind[EventKind["NilEvent"] = 0] = "NilEvent";
    EventKind[EventKind["PlayerHello"] = 1] = "PlayerHello";
    EventKind[EventKind["PlayerQuit"] = 2] = "PlayerQuit";
    EventKind[EventKind["PlayerJoined"] = 3] = "PlayerJoined";
    EventKind[EventKind["PlayerJoinedList"] = 4] = "PlayerJoinedList";
    EventKind[EventKind["PlayerHelloConfirm"] = 5] = "PlayerHelloConfirm";
    EventKind[EventKind["PlayerMovedList"] = 6] = "PlayerMovedList";
    EventKind[EventKind["PlayerMoved"] = 7] = "PlayerMoved";
})(EventKind || (EventKind = {}));
