// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
import * as flatbuffers from '../../flatbuffers/flatbuffers.js';
import { RawEvent } from '../../flatgen/game/raw-event.js';
export class EventList {
    bb = null;
    bb_pos = 0;
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsEventList(bb, obj) {
        return (obj || new EventList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsEventList(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new EventList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    events(index, obj) {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? (obj || new RawEvent()).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
    }
    eventsLength() {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
    }
    static startEventList(builder) {
        builder.startObject(1);
    }
    static addEvents(builder, eventsOffset) {
        builder.addFieldOffset(0, eventsOffset, 0);
    }
    static createEventsVector(builder, data) {
        builder.startVector(4, data.length, 4);
        for (let i = data.length - 1; i >= 0; i--) {
            builder.addOffset(data[i]);
        }
        return builder.endVector();
    }
    static startEventsVector(builder, numElems) {
        builder.startVector(4, numElems, 4);
    }
    static endEventList(builder) {
        const offset = builder.endObject();
        return offset;
    }
    static finishEventListBuffer(builder, offset) {
        builder.finish(offset);
    }
    static finishSizePrefixedEventListBuffer(builder, offset) {
        builder.finish(offset, undefined, true);
    }
    static createEventList(builder, eventsOffset) {
        EventList.startEventList(builder);
        EventList.addEvents(builder, eventsOffset);
        return EventList.endEventList(builder);
    }
}
