// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from '../../flatbuffers/flatbuffers.js';

import { EventKind } from '../../flatgen/game/event-kind.js';


export class KindHolder {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):KindHolder {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsKindHolder(bb:flatbuffers.ByteBuffer, obj?:KindHolder):KindHolder {
  return (obj || new KindHolder()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsKindHolder(bb:flatbuffers.ByteBuffer, obj?:KindHolder):KindHolder {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new KindHolder()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

kind():EventKind {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : EventKind.NilEvent;
}

static startKindHolder(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addKind(builder:flatbuffers.Builder, kind:EventKind) {
  builder.addFieldInt8(0, kind, EventKind.NilEvent);
}

static endKindHolder(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createKindHolder(builder:flatbuffers.Builder, kind:EventKind):flatbuffers.Offset {
  KindHolder.startKindHolder(builder);
  KindHolder.addKind(builder, kind);
  return KindHolder.endKindHolder(builder);
}
}
