// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
import * as flatbuffers from '../../flatbuffers/flatbuffers.js';
import { EventKind } from '../../flatgen/game/event-kind.js';
export class KindHolder {
    bb = null;
    bb_pos = 0;
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsKindHolder(bb, obj) {
        return (obj || new KindHolder()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsKindHolder(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new KindHolder()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    kind() {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readUint8(this.bb_pos + offset) : EventKind.NilEvent;
    }
    static startKindHolder(builder) {
        builder.startObject(1);
    }
    static addKind(builder, kind) {
        builder.addFieldInt8(0, kind, EventKind.NilEvent);
    }
    static endKindHolder(builder) {
        const offset = builder.endObject();
        return offset;
    }
    static createKindHolder(builder, kind) {
        KindHolder.startKindHolder(builder);
        KindHolder.addKind(builder, kind);
        return KindHolder.endKindHolder(builder);
    }
}
