// automatically generated by the FlatBuffers compiler, do not modify
export class Player {
    bb = null;
    bb_pos = 0;
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    id() {
        return this.bb.readInt32(this.bb_pos);
    }
    x() {
        return this.bb.readInt32(this.bb_pos + 4);
    }
    y() {
        return this.bb.readInt32(this.bb_pos + 8);
    }
    speed() {
        return this.bb.readInt32(this.bb_pos + 12);
    }
    movingLeft() {
        return !!this.bb.readInt8(this.bb_pos + 16);
    }
    movingRight() {
        return !!this.bb.readInt8(this.bb_pos + 17);
    }
    movingUp() {
        return !!this.bb.readInt8(this.bb_pos + 18);
    }
    movingDown() {
        return !!this.bb.readInt8(this.bb_pos + 19);
    }
    static sizeOf() {
        return 20;
    }
    static createPlayer(builder, id, x, y, speed, moving_left, moving_right, moving_up, moving_down) {
        builder.prep(4, 20);
        builder.writeInt8(Number(Boolean(moving_down)));
        builder.writeInt8(Number(Boolean(moving_up)));
        builder.writeInt8(Number(Boolean(moving_right)));
        builder.writeInt8(Number(Boolean(moving_left)));
        builder.writeInt32(speed);
        builder.writeInt32(y);
        builder.writeInt32(x);
        builder.writeInt32(id);
        return builder.offset();
    }
}
