// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
import * as flatbuffers from '../../flatbuffers/flatbuffers.js';
import { Player } from '../../flatgen/game/player.js';
export class PlayerJoined {
    bb = null;
    bb_pos = 0;
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsPlayerJoined(bb, obj) {
        return (obj || new PlayerJoined()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsPlayerJoined(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new PlayerJoined()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    player(obj) {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? (obj || new Player()).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
    }
    static startPlayerJoined(builder) {
        builder.startObject(1);
    }
    static addPlayer(builder, playerOffset) {
        builder.addFieldOffset(0, playerOffset, 0);
    }
    static endPlayerJoined(builder) {
        const offset = builder.endObject();
        return offset;
    }
    static createPlayerJoined(builder, playerOffset) {
        PlayerJoined.startPlayerJoined(builder);
        PlayerJoined.addPlayer(builder, playerOffset);
        return PlayerJoined.endPlayerJoined(builder);
    }
}
