// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
import * as flatbuffers from '../../flatbuffers/flatbuffers.js';
import { Player } from '../../flatgen/game/player.js';
export class PlayerMoved {
    bb = null;
    bb_pos = 0;
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsPlayerMoved(bb, obj) {
        return (obj || new PlayerMoved()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsPlayerMoved(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new PlayerMoved()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    player(obj) {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? (obj || new Player()).__init(this.bb_pos + offset, this.bb) : null;
    }
    static startPlayerMoved(builder) {
        builder.startObject(1);
    }
    static addPlayer(builder, playerOffset) {
        builder.addFieldStruct(0, playerOffset, 0);
    }
    static endPlayerMoved(builder) {
        const offset = builder.endObject();
        return offset;
    }
    static createPlayerMoved(builder, playerOffset) {
        PlayerMoved.startPlayerMoved(builder);
        PlayerMoved.addPlayer(builder, playerOffset);
        return PlayerMoved.endPlayerMoved(builder);
    }
}
