// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from '../../flatbuffers/flatbuffers.js';

import { EventKind } from '../../flatgen/game/event-kind.js';
import { Player } from '../../flatgen/game/player.js';


export class PlayerJoinedList {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PlayerJoinedList {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPlayerJoinedList(bb:flatbuffers.ByteBuffer, obj?:PlayerJoinedList):PlayerJoinedList {
  return (obj || new PlayerJoinedList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPlayerJoinedList(bb:flatbuffers.ByteBuffer, obj?:PlayerJoinedList):PlayerJoinedList {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PlayerJoinedList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

kind():EventKind {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : EventKind.NilEvent;
}

players(index: number, obj?:Player):Player|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Player()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 20, this.bb!) : null;
}

playersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startPlayerJoinedList(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addKind(builder:flatbuffers.Builder, kind:EventKind) {
  builder.addFieldInt8(0, kind, EventKind.NilEvent);
}

static addPlayers(builder:flatbuffers.Builder, playersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, playersOffset, 0);
}

static startPlayersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(20, numElems, 4);
}

static endPlayerJoinedList(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPlayerJoinedList(builder:flatbuffers.Builder, kind:EventKind, playersOffset:flatbuffers.Offset):flatbuffers.Offset {
  PlayerJoinedList.startPlayerJoinedList(builder);
  PlayerJoinedList.addKind(builder, kind);
  PlayerJoinedList.addPlayers(builder, playersOffset);
  return PlayerJoinedList.endPlayerJoinedList(builder);
}
}
