// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
import * as flatbuffers from '../../flatbuffers/flatbuffers.js';
import { EventKind } from '../../flatgen/game/event-kind.js';
export class PlayerQuit {
    bb = null;
    bb_pos = 0;
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsPlayerQuit(bb, obj) {
        return (obj || new PlayerQuit()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsPlayerQuit(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new PlayerQuit()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    kind() {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readUint8(this.bb_pos + offset) : EventKind.NilEvent;
    }
    id() {
        const offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
    }
    static startPlayerQuit(builder) {
        builder.startObject(2);
    }
    static addKind(builder, kind) {
        builder.addFieldInt8(0, kind, EventKind.NilEvent);
    }
    static addId(builder, id) {
        builder.addFieldInt32(1, id, 0);
    }
    static endPlayerQuit(builder) {
        const offset = builder.endObject();
        return offset;
    }
    static createPlayerQuit(builder, kind, id) {
        PlayerQuit.startPlayerQuit(builder);
        PlayerQuit.addKind(builder, kind);
        PlayerQuit.addId(builder, id);
        return PlayerQuit.endPlayerQuit(builder);
    }
}
