// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from '../../flatbuffers/flatbuffers.js';

export class PlayerHello {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PlayerHello {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPlayerHello(bb:flatbuffers.ByteBuffer, obj?:PlayerHello):PlayerHello {
  return (obj || new PlayerHello()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPlayerHello(bb:flatbuffers.ByteBuffer, obj?:PlayerHello):PlayerHello {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PlayerHello()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startPlayerHello(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
}

static endPlayerHello(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPlayerHello(builder:flatbuffers.Builder, id:number):flatbuffers.Offset {
  PlayerHello.startPlayerHello(builder);
  PlayerHello.addId(builder, id);
  return PlayerHello.endPlayerHello(builder);
}
}
